package handler;

/**
 * SingleRequest class stands for a single ticket request for the seat.
 */
public class SingleRequest {

  private String name;
  private String phone;
  private boolean wheelSeatFlag;
  private boolean printedFlag;
  private Seat seat;

  /**
   * The booker's name who makes this request.
   * @return the booker's name
   */
  public String getName() {
    return name;
  }

  /**
   * Setter of the booker's name.
   * @param name booker's name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Getter of the booker's phone number.
   * @return phone number
   */
  public String getPhone() {
    return phone;
  }

  /**
   * Setter of the booker's phone number.
   * @param phone phone number
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * Whether the booker requests a seat for a wheel chair.
   * @return true if the booker requests a seat for a wheel chair.
   */
  public boolean isWheelSeatFlag() {
    return wheelSeatFlag;
  }

  /**
   * Setter of Whether the booker requests a seat for a wheel chair.
   * @param wheelSeatFlag true if the booker requests a seat for a wheel chair.
   */
  public void setWheelSeatFlag(boolean wheelSeatFlag) {
    this.wheelSeatFlag = wheelSeatFlag;
  }

  /**
   * Whether the ticket generated by this request has been printed.
   * @return true if the ticket has been printed
   */
  public boolean isPrintedFlag() {
    return printedFlag;
  }

  /**
   * Setter of Whether the ticket generated by this request has been printed.
   * @param printedFlag true if the ticket has been printed
   */
  public void setPrintedFlag(boolean printedFlag) {
    this.printedFlag = printedFlag;
  }

  /**
   * Seat assigned to this request. Null if no seat has been assigned to this request.
   * @return seat
   */
  public Seat getSeat() {
    return seat;
  }

  /**
   * Setter of the seat assigned to the request.
   * @param seat seat assigned
   */
  public void setSeat(Seat seat) {
    this.seat = seat;
  }

  /**
   * Constructor.
   * @param name booker's name
   * @param phone booker's phone number
   * @param wheelSeatFlag whether the booker wants a seat for wheel chair or not
   */
  public SingleRequest(String name, String phone, boolean wheelSeatFlag) {
    this.name = name;
    this.phone = phone;
    this.wheelSeatFlag = wheelSeatFlag;
    this.printedFlag = false;
    this.seat = null;
  }
}
